### ISSUE TITLE
Any research paper related to this?

### ISSUE THREAD

**Issue by saifhassan** [andreasveit/coco-text#17]
Any paper you have written for this contribution? Actually I need details of this code: features, accuracy, precision, architecture etc.

**Comment by andreasveit** [comment]
Thank you for your interest in our work. You can find the paper here: https://arxiv.org/pdf/1601.07140.pdf
Please note that since the release, we have changed the evaluation procedure (not captured in the paper yet). Please refer to the ICDAR2017 Robust Reading Challenge on COCO-Text for details on evaluation and baselines. http://rrc.cvc.uab.es/?ch=5
